### PR TITLE
fix(webapp): align httpcore5 version with httpclient5 5.6.3

### LINKED ISSUE #2295: integration-tests: NoClassDefFoundError IOFunction after httpclient5 5.6.3 bump
## Problem

After #2270/#2271 bumped `httpclient5` to 5.6.3, the `integration-tests` CI job fails on `master` with:

```
java.lang.NoClassDefFoundError: org/apache/hc/core5/io/IOFunction
```

Affected tests include `TestControllerIT`, `TracingControllerIT`, and `DynamicMockRestControllerIT`.

## Root cause

`httpclient5:5.6.3` requires `httpcore5:5.4.3+` (class `org.apache.hc.core5.io.IOFunction` is not present in `httpcore5:5.3.6`).

Spring Boot 4.0.7 BOM pins `httpcore5` to **5.3.6**, overriding the transitive version declared by `httpclient5`.

Last green `master` CI: before the httpclient5 bumps (`c0a19698`).

## Proposed fix

Explicitly declare `httpcore5` and `httpcore5-h2` at **5.4.3** in `webapp/pom.xml` (and optionally `minions/async/pom.xml` for consistency).

## AI disclosure

Issue drafted with assistance from an AI coding assistant (Cursor).

### PR DESCRIPTION
**Pull request by gozen59**
## Summary

- Pin `httpcore5` and `httpcore5-h2` to 5.4.3 in `webapp/pom.xml` and `minions/async/pom.xml`
- Fixes `integration-tests` CI failures introduced after #2270/#2271 bumped `httpclient5` to 5.6.3

Fixes #2295

## Problem

Spring Boot 4.0.7 BOM pins `httpcore5` to 5.3.6, but `httpclient5` 5.6.3 requires `httpcore5` 5.4.3+ (`org.apache.hc.core5.io.IOFunction` is missing in 5.3.6).

## Test plan

- [x] `mvn dependency:tree` shows `httpcore5:5.4.3` (no longer downgraded to 5.3.6)
- [x] `TestControllerIT#testOpenAPITesting` passes locally
- [x] `integration-tests` CI job passes

## AI disclosure

This pull request was prepared with assistance from an AI coding assistant (Cursor). The human author is responsible for reviewing, testing, and understanding the changes.

### CODE REVIEW

**Comment by lbroudoux** [comment]
Great catch! I trusted the compatibility report and didn't analyse this regression. Thanks for the quick fix!

**Review by lbroudoux — APPROVED** [review]
LGTM. Thanks!
